### PR TITLE
Updated color bg for search bar and moved snackbar to the top :)

### PR DESCRIPTION
**Pull request by philiparpin**

### CODE REVIEW

**Review by jorge-caballero — CHANGES_REQUESTED** [review]
Can we make the add placeholder text to the search bar?

**Comment by jorge-caballero** [comment]
@philiparpin this is a great improvement - it strikes the balance of drawing attention to key nav elements, info modals, and doesn't crowd the viewport. 

the one area we could stand to improve is in making the search area larger and to add placeholder suggested values so users understand what they can search. in our case, that would be something like "94025", "Montgomery", "NYU"

**Review by afahy — APPROVED** [review]

**Comment by philiparpin** [comment]
@jorge-caballero Do we think the examples of places they can search is necessary? I was looking at Google Maps: https://www.google.com/maps and they don't seem to put suggestions in their search bar and simply just tell users to "Search Google Maps". Since our search is universal, there's no way we'd have enough space to showcase an exhaustive list. What if instead, we changed the placeholder text to "Search for a location"?

**Comment by philiparpin** [comment]
We could also add a small question mark to the right of the search bar that shows examples when hovered if you think people are really having trouble with that. Best thing I can recommend though is to get some user interviews setup and use those to get feedback. Happy to help with those since I've done a lot of them before.

**Comment by jorge-caballero** [comment]
@philiparpin  your point is well-taken regarding search suggestions in the placeholder text. let's put that on ice for now. i'll make the width of the search field into a separate trello card

**Pull request merged**
